### ISSUE TITLE
📝[Docs]: Clarifying Protocols - IBus, SBus, CRSF for Arduino Library

### ISSUE THREAD

**Issue by Witty-Wizard** [Witty-Wizard/SerialIO#13]
# Overview
Currently, our Arduino library lacks comprehensive documentation on the various protocols supported, notably IBus, SBus, and CRSF.

## What we want?
We need to fix this by writing clear explanations about IBus, SBus, and CRSF in our library documentation. We want users to understand these methods easily so they can use them effectively in their projects.

## Tasks
- [x] Write Documentation for Sbus
- [x] Write Documentation for Ibus
- [x] Write Documentation for CRSF
