### ISSUE TITLE
✨[FEATURE]: Add Support for Software Serial

### ISSUE THREAD

**Issue by Witty-Wizard** [Witty-Wizard/SerialIO#25]
# Overview
Implement Software Serial support, this helps with boards that do not have UART peripheral or 8-bit boards that do not support non-conventional baud rates like in the case of SBus(10000 Bauds per second)

## Tasks
- [ ] Implement a construction overload that accepts PIN as input
- [ ] Create a new SoftSerial object using those pins
- [ ] Check with existing hardware
